### ISSUE TITLE
Quiz incomplete

### ISSUE THREAD

**Issue by moulikbhardwaj** [moulikbhardwaj/nimbus2021#3]
Endpoints related to quiz are needed to be done.
Get request to either 
/departments/{department}/quiz/{quiz_id}/
or 
/quiz/{quiz_id}/

Should return a list of questions with options, with number of questions specified in quiz model.

There should also be an endpoint, that will check the answers given by user, and return total number of correct answers.
the endpoint can be same as before, or can make new ones.

**Comment by spiderxm** [comment]
assign me this issue
