### ISSUE TITLE
Omeagle clone

### ISSUE THREAD

**Issue by moulikbhardwaj** [moulikbhardwaj/nimbus2021#4]
We need to start an app for omeagle clone.
We mainly need to store the call records(who were calling, from what time to what time), and a report functionality (who reported whom, in what call, any comment/report reason etc.)
There may be a need to change User model for saving information about numbers of reports against the user, and a boolean value whether the user is allowed to use the functionality or not.

**Comment by Anshit01** [comment]
Assign this to me
