### ISSUE TITLE
Events app

### ISSUE THREAD

**Issue by moulikbhardwaj** [moulikbhardwaj/nimbus2021#6]
The app that will handle events/exhibitions and talks etc, is incomplete.
The following functionality is required

1. Creation of Events/talks/exhibitions/workshops
    - Events may be departmental level or institutional level.
    - Event has following information
        - Abstract - Type: text
        - Name - Type: text
        - info - Type: text
        - venue - Type: text
        - date - DateTime
        - image - URL
        - regUrl - URL
        - type - int
            - 0 for department event
            - 1 for institute event
            - 2 for talks
            - 3 for exhibitions
            - 4 for workshops

2. Fetching of events etc.
    - Should return all events/talks, or whatever resource is asked for that are on or after current day. 

Endpoints may be 
GET:
/departmentEvents
/instituteEvents
/talks
/exhibitions
/workshops

POST:
/departmentEvents
/instituteEvents
/talks
/exhibitions
/workshops

**Comment by Anshit01** [comment]
assign this to me

**Comment by moulikbhardwaj** [comment]
There are going to be a bit of changes in this app. We now have to collaborate with Web Team for this app, and there are going to be some changes regarding custom authentication. It might get a bit difficult as some of classes need to be overridden, and new classes are to be made. So, i am assigning this to myself.
