### ISSUE TITLE
Core team and sponsor list

### ISSUE THREAD

**Issue by moulikbhardwaj** [moulikbhardwaj/nimbus2021#7]
An app that will handle requests related to core team and sponsor lists.

Core Team should have following model
- name - Type: text
- position - Type: text
- image - Type: URL

Sponsors should have following model
- name - Type:text
- image - Type:URL

Endpoints:
GET:
- /coreTeam - return all memebers of core team
- /sponsors - return all sponsors

**Comment by mhsalmaan** [comment]
Assign this to me
